import type { NextPage } from "next";
import Head from "next/head";
import { Main } from "../src/components/Main";
import { Footer } from "../src/components/Footer";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Index Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main page="index" />

      <Footer />
    </div>
  );
};

export default Home;
